#!/usr/bin/env bash
# Configures and Nginx server to listen on port 80

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for al active IPv4 IPs
in -s /etc/nginx'sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
