#!/usr/bin/env bash
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
# Modify the Nginx configuration to listen on port 80
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
service nginx restart
